### ISSUE TITLE
where to get the essay?

### ISSUE THREAD

**Issue by XhqGlorry11** [amoussawi/caffe#1]
Hi, very glad to see your excellent work. I'd like to know where I can get the full text of your essay:An FPGA-Accelerated Design for Deep Learning Pedestrian Detection in Self-Driving Vehicles. Please help. Thx.

**Comment by amoussawi** [comment]
Hi, thank you for your interest. Sorry i forgot to put (to appear). The paper should be available online by April 20 [here](http://feaweb.aub.edu.lb/feasac/16/index.html).

**Comment by XhqGlorry11** [comment]
@amoussawi Nice to get your reply. But I find something wrong. When I run the script to train the model by executing command "python examples/ssd/ssd_caltech_512_ft.py", I get the error saying: 
Check failed: num_priors_ * loc_classes_ * 4 == bottom[0]->channels() (54612 vs. 163836) Number of priors must match number of location predictions.
And I go back to the script and find that, in the script, only ONE aspect ratio(0.41) is defined for each layer when doing mbox_priorbox generation. But the prediction part generates THREE times aspect ration, which results in dimension mismatch problem. Please check. thx

**Comment by amoussawi** [comment]
This happens when fine-tuning. The convolution predictors are mismatching with the ones in pre-trained model. There are two variables in the script called "conf_postfix" and "loc_postfix". Assign "_ft" to them for example. I was changing them for only one iteration and when I have a solverstate I change them back as they were so they don't mean anything special. Anyway I will fix that bug.

**Comment by XhqGlorry11** [comment]
@amoussawi Hi , thanks so much. Still a little bit confused. Please help to check if I am understanding correctly. The caffemodel file(VGG_VOC0712Plus_SSD_512x512_ft_iter_160000.caffemodel) that you want to fine tune is fixed and it has 9 aspect ratios for conv4_3 layer. But you find 3 aspect ratios for conv4_3 layer is enough for pedestrian detection on caltech dataset and you dont want to use 9 aspect ratios any more. Is that correct.....

**Comment by XhqGlorry11** [comment]
@amoussawi Hi thanks so much. But I am still very confused. I mean the train.prototxt, test.prototxt and deploy.prototxt are all generated by the python script. The dimensions of predictors and mbox_priorbox should be the same. I mean, if conv4_3 has 3 aspect ratios(or sizes) and there are m classes, then mbox_prior should generate 4n data, loc predictors should generate 4n data, and conf predictors should generate mn data.  Did you change the python script for generating *.prototxt?

**Comment by XhqGlorry11** [comment]
@amoussawi Hi thanks so much. But I am still very confused. I mean the train.prototxt, test.prototxt and deploy.prototxt are all generated by the python script. The dimensions of predictors and mbox_priorbox should be the same. I mean, if conv4_3 has n aspect ratios(or sizes) and there are m classes, then mbox_prior should generate 4n data, loc predictors should generate 4n data, and conf predictors should generate mn data. But for now, conv4_3 has 3 sizes and conv4_3_norm_mbox_priorbox generate 49152(64*64*4*3) data,but conv4_3_norm_loc generate 64*64*4*9. Did you change the python script for generating *.prototxt?

**Comment by XhqGlorry11** [comment]
@amoussawi Hi thanks so much. But I am still very confused. I mean the train.prototxt, test.prototxt and deploy.prototxt are all generated by the python script. The dimensions of predictors and mbox_priorbox should be the same. I mean, if conv4_3 has n aspect ratios(or sizes) and there are m classes, then mbox_prior should generate 4n data, loc predictors should generate 4n data, and conf predictors should generate mn data. But for now, conv4_3 has 3 sizes and conv4_3_norm_mbox_priorbox generate 49152(64x64x4x3) data,but conv4_3_norm_loc generate 64x64x4x9. Did you change the python script for generating *.prototxt?

**Comment by amoussawi** [comment]
On a specific layer, if you have `n` aspect ratios and `m` scales and `c` classes,  then you have `c*n*m` predictors for confidence and `4*c*n*m` predictors for location. So in our case there are 6 predictors for conv4_3_loc and 12 predictors for conv4_3_conf. Which is as shown in the deploy.prototxt.

**Comment by XhqGlorry11** [comment]
@amoussawi Well, I think for conv4_3_norm(whose dimension is 64*64), it has 1 aspect ratio and 3 scales. So the conv4_3_norm_mbox_priorbox's dimension should be 49152(12*64*64), and conv4_3_norm_mbox_loc's dimension should be 12*64*64, and conv4_3_norm_mbox_loc's dimension should be 6*64*64. However in fact, conv4_3_norm_mbox_priorbox's dimension is 49152(12*64*64) and conv4_3_norm_mbox_loc's dimension is 36*64*64, and conv4_3_norm_mbox_loc's dimension should be 18*64*64. And this results in dimension mismatch problem.

**Comment by XhqGlorry11** [comment]
@amoussawi Well, I think for conv4_3_norm(whose dimension is 6464), it has 1 aspect ratio and 3 scales. So the conv4_3_norm_mbox_priorbox's dimension should be `49152(12*64*64),` and conv4_3_norm_mbox_loc's dimension should be `12*64*64`, and conv4_3_norm_mbox_loc's dimension should be `6*64*64`. However in fact, conv4_3_norm_mbox_priorbox's dimension is `49152(12*64*64)` but conv4_3_norm_mbox_loc's dimension is `36*64*64`, and conv4_3_norm_mbox_loc's dimension is `18*64*64`. And this results in dimension mismatch problem.

**Comment by XhqGlorry11** [comment]
@amoussawi Well, I think for conv4_3_norm(whose dimension is `64*64`), it has 1 aspect ratio and 3 scales. So the conv4_3_norm_mbox_priorbox's dimension should be `49152(12(3*4)*64*64)`, and conv4_3_norm_mbox_loc's dimension should be `12(3*4)*64*64`, and conv4_3_norm_mbox_loc's dimension should be `6(3*2)*64*64`. However in fact, conv4_3_norm_mbox_priorbox's dimension is `49152(12(3*4)*64*64)` but conv4_3_norm_mbox_loc's dimension is `36(9*4)*64*64`, and conv4_3_norm_mbox_loc's dimension is `18(9*2)*64*64`. And this results in dimension mismatch problem. And the wrong number(36,18) comes from deploy file.
Maybe you can run the examples/ssd/ssd_caltech_512_ft.py script of the github codes and check the error and *.prototxt and figure out what's going wrong.

**Comment by XhqGlorry11** [comment]
@amoussawi Well, I think for conv4_3_norm(whose dimension is `64*64`), it has 1 aspect ratio and 3 scales. So the conv4_3_norm_mbox_priorbox's dimension should be `49152(12(3*4)*64*64)`, and conv4_3_norm_mbox_loc's dimension should be `12(3*4)*64*64`, and conv4_3_norm_mbox_conf's dimension should be `6(3*2)*64*64`. However in fact, conv4_3_norm_mbox_priorbox's dimension is `49152(12(3*4)*64*64)` but conv4_3_norm_mbox_loc's dimension is `36(9*4)*64*64`, and conv4_3_norm_mbox_conf's dimension is `18(9*2)*64*64`. And this results in dimension mismatch problem. And the wrong number(36,18) do comes from deploy file.
Maybe you can run the examples/ssd/ssd_caltech_512_ft.py script of the github codes and check the error and *.prototxt files to figure out what's going wrong.

**Comment by XhqGlorry11** [comment]
@amoussawi Hi,I want to explain my points clearer. All the *.prototxt files are generated by the python script, but when we run the demo it goes wrong. And I find out the reason, it is because the dimension of layers within *.prototxt don't match. Since all these *.prototxt files are generated by python script and now they go wrong, I think you must have changed the *.prototxt files generation part within the python script. I'm wandering what has been changed and why, and the method or procedure to make it correct to train the model. THX ^_^.

**Comment by amoussawi** [comment]
There's nothing wrong. You are computing the number of elements in the whole predictions matrix. You have 6 confidence predictors  and each predictor convolve over the input feature map and output 64x64 matrix and each value in that matrix is the confidence prediction value of the corresponding default bounding box. Same applies for the location regression.

**Comment by amoussawi** [comment]
where are you getting these values from?

**Comment by XhqGlorry11** [comment]
@amoussawi There are 2 ways to get these values. First, check the *.prototxt files. Second, check the logfile in $CAFFE_ROOT/jobs/VGGNet/caltech/SSD_512x512_ft/VGG_caltech_SSD_512x512_ft.log.

**Comment by XhqGlorry11** [comment]
@amoussawi Hi, since you have managed to get the training and testing result on caltech dataset, did you use the script: "examples/ssd/ssd_caltech_512_ft.py" to train 512x512 model? If so, what modifications did you make to conduct the training successfully?

**Comment by XhqGlorry11** [comment]
@amoussawi Hi, my friend, I guess I've figured out what's going wrong. Maybe I should change another computer which hasn't installed any version of caffe before. Otherwise, the original pycaffe module may overwrite the pycaffe of your work when we conduct "import caffe" in a python script.

**Comment by XhqGlorry11** [comment]
@amoussawi And it seems that I have understood why you use variables: conf_postfix and loc_postfix. Please help to check whether I'm understanding correctly. The model(VGG_VOC0712Plus_SSD_512x512_ft_iter_160000.caffemodel) that you used for fine tune is fixed, but the dimensions for loc and conf predictor parts are not appropriate with your case. So you are just going to use the pre-trained model to initialize conv1_*, conv2_*,.....conv10_2 layers. As for *_mbox_loc layers and *_mbox_conf layers, you don't use the pre-trained model to initialize because the dimensions dismatch. And you must change the names of conf and loc predictor parts in your model to be not the same with those in the pre-trained model to avoid raising errors. And you use xavier method to initialize loc and conf predictors layers. Am I right? ^ ^

**Comment by XhqGlorry11** [comment]
@amoussawi And it seems that I have understood why you use these 2 variables: conf_postfix and loc_postfix. Please help to check whether I'm understanding correctly. The model(VGG_VOC0712Plus_SSD_512x512_ft_iter_160000.caffemodel) that you use for fine tune is fixed, but the dimensions for loc and conf predictor parts are not appropriate with your case. So you are just going to use the pre-trained model to initialize conv1_*, conv2_*,.....conv10_2 layers of your model. As for *_mbox_loc layers and *_mbox_conf layers, you don't use the pre-trained model to initialize because the dimensions dismatch. And you must change the names of conf and loc predictor parts in your model to be not the same with those in the pre-trained model to avoid raising errors. And you use xavier method to initialize loc and conf predictors layers. Am I right? ^ ^

**Comment by amoussawi** [comment]
Yes you are right. Just give it some time and you will understand everything :)

**Comment by XhqGlorry11** [comment]
@amoussawi that's cool！thx
