### ISSUE TITLE
Cannot creat lmdb in the 4th step in Preparation

### ISSUE THREAD

**Issue by henrychen1620** [amoussawi/caffe#2]
### Issue summary
Hi, first I want to thank you for the effort of doing Caltech on SSD. Here is my question:
I do step 4 in the Preparation step(I didn't do step 3 since I don't need evaluation yet), and I put the downloaded Caltech file in /home/data/caltech_code/. But when I execute ./data/caltech/creat_list.sh, it shows these two messages:

Create list for caltech trainval...
ls: cannot access '/home/paris/caffe/data/caltech/trainval/images//': No such file or directory
ls: cannot access '/home/paris/caffe/data/caltech/trainval/images//': No such file or directory
and ...
Create list for caltech test...
ls: cannot access '/home/paris/caffe/data/caltech/test/images//': No such file or directory
ls: cannot access '/home/paris/caffe/data/caltech/test/images//': No such file or directory

I'm don't know where I've done wrong or do I miss any step?

**Comment by amoussawi** [comment]
you need the 3rd step in order to generate the dataset using `extractDatasets.m` matlab script. (btw i just uploaded the pretrained model, you can use it if you don't want to train the model).

**Comment by henrychen1620** [comment]
Thanks again, but I have an another question: 
1. Where should I put this pretrained model? should I put it in /home/caffe/model/VGGNet/caltech/ ?
2. After placing the deploy and .caffemodel in the right place, should I still execute the "ssd_caltech_webcam_ft.py" file to test using webcam?

**Comment by amoussawi** [comment]
yes you should put it in `$CAFFE_HOME/model/VGGNet/caltech/SSD_512x512_ft/`. you can test on video using `ssd_caltech_video_ft.py`. (I updated the pre-trained model zip file to account for directory structure).

**Comment by henrychen1620** [comment]
Hi, but I follow the instruction you give and execute this code "ssd_caltech_video_ft.py". It shows: 

"Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_loc'; shape mismatch.  Source param shape is 12 512 3 3 (55296); target param shape is 36 512 3 3 (165888). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer."

I use your pretrained model you post

**Comment by amoussawi** [comment]
sorry but I'm pretty sure the script is correct, I just tested it. Please check your script in case you have changed something. The source param shape is correct. The target param shape is the wrong one which is set by the script.

**Comment by henrychen1620** [comment]
Thanks for your patient, so let me clear the instruction again:

Step 1. Download the zip you uploaded from here: https://www.dropbox.com/s/1zvmbj2gtchdxhm/SSD_512x512_ft.zip?dl=0

and it contains 5 files:
1.1)deploy.prototxt
1.2)ssd_caltech_512_ft.py
1.3)test.prototxt
1.4)train.prototxt
1.5)VGG_caltech_SSD_512x512_ft_iter_20000.caffemodel

Step 2. Rename the download folder to SSD_512x512_ft put this download folder in   $CAFFE_HOME/model/VGGNet/caltech/ after extracting it. 

Step 3. execute both codes "ssd_caltech_video_ft.py" and "ssd_caltech_webcam_ft.py", they should work

Am I right? Thanks for the patient again!

**Comment by amoussawi** [comment]
Yes. and Actually all you need is `.caffemodel` file because the script will generate its own `.prototxt` file.

**Comment by henrychen1620** [comment]
That's strange, I still face the same problem

**Comment by amoussawi** [comment]
Ah wait. do a `git pull`, I made recently an update on the video script that you might not have.
