### ISSUE TITLE
Question about ETH & TUD-Brussel dataset and hard negative mining

### ISSUE THREAD

**Issue by fanyang16120029** [amoussawi/caffe#8]
Hi @amoussawi , I have two questions in my SSD training on Caltech.

1. Have you used hard negative mining during training?

2. In your paper, you have mentioned the ETH and TUD-Brussels dataset results additional 4000 images, but I could only find 2313 images with pedestrian annotations. 
  (ETH setup1 ~ set00 V000 999
                         set01 V001 451
                         set02 V002 354, 
   TUD ~ 507)

**Comment by amoussawi** [comment]
1. Hard negative mining is alreay being done by SSD as mentioned in their paper.

2. I don't remember the actual numbers, but anyway, the other images without annotations still contribute in negative samples.
